{% set name = "conda_deps" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 761d4b0f0aa18e3d3edf634c0d4026784f49445a14f7bcc1bb02d1fbbd755f17

build:
  number: 0
  skip: True  # [win or py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - conda_deps --help

about:
  home: https://github.com/cgat-developers/conda-deps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Generate conda environment files from Python source code'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
