{% set name = "conda_deps" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b33406a63c505238bc693c804bdf4de463570171edc1c3a4eeff80736af726cc

build:
  number: 0
  skip: True  # [win or py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - conda_deps --help

about:
  home: https://github.com/cgat-developers/conda-deps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Generate conda environment files from Python source code'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
