travis:
  secure:
    BINSTAR_TOKEN: XZzYyrKMSbhcn75rXKM+2zS4xR5t4dxDBvzEUA7vrjtDkVExauAKfj8xtmTW8Rj5C4l3tQS2vBUDj2Vh3R8MlzwkdYIEeudfCsBquZ/VAHAzs1rIR9Rw1YjghP8amYzG+6QV9y1G0Lg2EhR/viFDCvYJGGKHCaLb+Lw9Ws+zJhfTYFM0e49DshKeH/1f/ZRFTaGuQSmuwbdnt4r0e/0AYAOSu6+mw9qb8K2dSeSMltwdMtTZhByg30DBrNqLy20us2ZsbujW5gdoloH6tnMU3QAaioiZamTnh7nIpolHVDemQoWyDLjmOKA0/rsYGr3450PX3NKfTWph5N62d/yx+y7j/WA/rHdHBzOgLxQrGPyPp2h2pPd4nGABGk3SiF3pF4dTg0OsIg1Hcru6vjNrV0WYQ5sQwlj+0t1Z0Z2F3Ddx6iF3hwEkAqPockBVoonVvCDLBXS32391/0XSusIEoPJdTjVl7J10ufHEEqe1dSD6onnqCIj9fT5PHB0TfhGJ26q6DTkSPvTpZwOMlePrrql/tj+lJ5wcFSdlCCU44TIDWW6NMNxEHFy2KFpLq2RW803TZ4c8CaHNd7O3/F69f5yVB4S69tnyx79yzUmJU8Tq9S7sAsS3oQoq4//+9AOm+ayX1tKTT87G5W3bOPC7/MxvAicd6tmNnbAehQyKesw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
